### PR TITLE
fix(treespec): memorize ongoing `repr` / `hash` calls to resolve infinite recursion under self-referential case

### LINKED ISSUE #81: [BUG] Potential infinite recursion on `repr(treespec)` / `hash(treespec)` when the node metadata references the `treespec` itself
### Required prerequisites

- [X] I have read the documentation <https://optree.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/metaopt/optree/issues) that this hasn't already been reported. (comment there if it has.)

### What version of OpTree are you using?

0.9.2

### System information

- Install from source
- Python version: 3.11.5

### Problem description

The `treespec` representation calls `repr` / `hash` for the node metadata for each node. When the node metadata references the `treespec` itself, this will cause infinite recursion of calling `repr(treespec)` / `hash(treespec)`.

Note that this situation is almost impossible to happen in the real world.

### Reproducible example code

The Python snippets:

```python
import optree


class Holder:
    def __init__(self, value):
        self.value = value

    def __eq__(self, other):
        return isinstance(other, Holder) and self.value == other.value

    def __hash__(self):
        return hash(self.value)

    def __repr__(self):
        return f'Holder({self.value!r})'


key = Holder('a')

treespec = optree.tree_structure({key: 0})
print(treespec)  # -> PyTreeSpec({Holder('a'): *})

key.value = 'b'
print(treespec)  # -> PyTreeSpec({Holder('b'): *})

key.value = treespec  # self reference
print(treespec)  # -> RecursionError
print(hash(treespec))  # -> RecursionError
```

### Traceback

```pytb
Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/optree/test.py", line 27, in <module>
    print(treespec)  # -> RecursionError
    ^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 15, in __repr__
    return f'Holder({self.value!r})'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 246 more times]
RecursionError: maximum recursion depth exceeded while getting the repr of an object

Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/optree/test.py", line 27, in <module>
    print(hash(treespec))  # -> RecursionError
          ^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/optree/test.py", line 12, in __hash__
    return hash(self.value)
           ^^^^^^^^^^^^^^^^
  [Previous line repeated 330 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by XuehaiPan**
## Description

Describe your changes in detail.

Add a set to memorize ongoing `repr` / `hash` calls to resolve infinite recursion under self-referential case.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [X] I have raised an issue to propose this change ([required](https://github.com/metaopt/optree/issues) for new features and bug fixes)

Fixes #81

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [X] I have read the [CONTRIBUTION](https://github.com/metaopt/optree/blob/HEAD/CONTRIBUTING.md) guide. (**required**)
- [X] My change requires a change to the documentation.
- [X] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [X] I have updated the documentation accordingly.
- [X] I have reformatted the code using `make format`. (**required**)
- [X] I have checked the code using `make lint`. (**required**)
- [X] I have ensured `make test` pass. (**required**)

### CODE REVIEW

File: include/treespec.h [hunk 1]
```diff
@@ -201,17 +204,34 @@ class PyTreeSpec {
...
-        return h;
+    }
+
+    template <typename H>
+    friend H AbslHashValueImpl(H h, const PyTreeSpec &t) {
+        return H::combine(std::move(h), t.m_traversal, t.m_none_is_leaf, t.m_namespace);
     }
 
     template <typename H>
     friend H AbslHashValue(H h, const PyTreeSpec &t) {
```
Comment (JieRen98) [inline include/treespec.h:217]: Why friend here

**Review by JieRen98 — CHANGES_REQUESTED** [review]

File: include/treespec.h (hunk 1 above)
Comment (XuehaiPan) [reply include/treespec.h:217]: This is required by the abseil-cpp hash library. Otherwise, it will raise `PoisonedHash` error during the compilation time.

Comment (JieRen98) [reply include/treespec.h:217]: I checked [official docs](https://abseil.io/docs/cpp/guides/hash). Seems to be an implementation of a function rather than a class method.

**Review by JieRen98 — APPROVED** [review]
